# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalenderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
            ],
            options={
                'verbose_name': 'Calender Event',
                'verbose_name_plural': 'Calender Events',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=uuid.UUID('f76ec671-d9eb-4ab7-99d4-989d4cf9109a'), max_length=50, verbose_name='Username')),
                ('person_type', models.CharField(choices=[('1', 'Candidate'), ('2', 'Interviewer')], default='1', max_length=1, verbose_name='Person Type')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.AddField(
            model_name='calenderevent',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ops.Person'),
        ),
    ]
