# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-07 01:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ops', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CalenderEvent',
            new_name='CalendarEvent',
        ),
        migrations.AlterField(
            model_name='person',
            name='username',
            field=models.CharField(default=uuid.UUID('d81bc2ec-7e3a-4db9-8e07-1f868bfdc852'), max_length=50, verbose_name='Username'),
        ),
    ]
